language: java
install: TERM=dumb gradle setupCIWorkspace --stacktrace
script: TERM=dumb gradle build --stacktrace
after_success:
- TERM=dumb gradle uploadFtp --stacktrace
- TERM=dumb gradle updateJson --stacktrace
branches:
  only:
  - master
  - development
env:
  global:
  - secure: BsEv2ZXQoTPrNLrMN746bVJUDFZXBfCD4+g/7jGMurEoV1YsLuoFVdH0j8JE4CD3PkCpvC5cmKJBcynHCBBltmJCBqxdtbC8nYa8QC1t1K6PfHLnrJ2VhXgMrER8iHgsKR2sl6VT9txqlyXlmdWCIC/PakNJn8dwiPH5ZYcw5lg=
  - secure: sl9IoVHp+ovXyemeenorc5ak2J+gx2xNyd5SEEh6pQvBV7nYgTLdZT6B+yAq8uydGsfvuYyuAbWkASmSX7oS+z6ksd38aiGjwi33kHYu1z1SmqZZl2SFgOCzJC7Oves1uq6w6vqhtkkdxmBMTe3a920tbyxRszhTyv5iqrT+ZPg=
  - secure: ck2110iqnx8loTEjpiyxgbOHdhnY+UYWWaurRZHURH2ivrqNMfonkgwMxMYhY0pmssZSINFEb9bkWKJBMxovsOsjdyYfezFX7CQsdS92gO2zY886fCcYapBbd2WM5Utf3quyUUSmz7G59NhGSCAo7pfwDFGMlk5/s6i113Zg5Eg=
  - secure: puD21uZn603i7qGDVAi79WRnomaKdPtJjDOXWMH+9RSq1r2pq8qmU4VATFrdY43mMEXQLiWxbR/9T0z7bqjnC6oapC3kQcUDMljQLG6SAJyMrU2etwigTdYs2HTO/pMPUer/gRHUtC8sd38VG6LyKsatBKdgiCbTawLr5HzF4Ng=